[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_livecoding_modules = "livecoding"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LIVECODING_MODULES,LOCALFOLDER"

[tool.ruff]
target-version = "py312"
line-length = 88
exclude = ["**/migrations/*"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
extend-select = ["E501"]
select = ["E4", "E7", "E9", "F", "B", "I"]
ignore = ["B904", "B027", "B018", "B019"]
unfixable = ["B"]

[tool.pytest.ini_options]
addopts = "-ra -v -s -q"
testpaths = [
    "tests",
]

markers = [
    "livecoding",
]

[tool.coverage.run]
omit = [
    # omit django migrations and project files
    "livecoding/wsgi.py",
    "livecoding/asgi.py",
    "manage.py",
    "**/urls.py",
    "livecoding/settings.py",
    "server/*.py",
    "gunicorn.conf.py",
    "gunicorn.asgi.conf.py",
    "env_check.py"
]

[tool.coverage.report]
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:"
]
